### ISSUE TITLE
Azure Pipeline shallow fetch =1 by default

### ISSUE THREAD

**Issue by kkazala** [MicrosoftDocs/azure-devops-yaml-schema#46] opened 2022-09-28 17:02 UTC
Newly created pipelines now have shallow fetch enabled and set to 1 by default:
![image](https://user-images.githubusercontent.com/22429087/192844408-8029b7b3-a646-4b74-891c-39558ee35d19.png)

Not sure since when this happens, but... perhaps it would be useful to mention it in this documentation?
I also opened this issue here: https://github.com/MicrosoftDocs/azure-devops-docs/issues/12732 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b28abf7f-ecdf-8037-acd9-722690424372
* Version Independent ID: b28abf7f-ecdf-8037-acd9-722690424372
* Content: [steps.checkout definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines)
* Content Source: [content/steps-checkout.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment] 2022-09-28 19:45
Closing as duplicate of https://github.com/MicrosoftDocs/azure-devops-docs/issues/12732.

cc @steved0x for awareness

**Closed by WilliamAntonRohm** 2022-09-28 19:45 UTC
Labels: documentation, duplicate, Pri1, devops/prod, devops-cicd/tech

**Comment by steved0x** [comment] 2022-09-30 15:19
This has been added to the documentation and should be live shortly.

https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#remarks

https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#shallow-fetch

Thank you for letting us know.
